version: "3.8"
services:
  database:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  patient-service:
    build:
      context: .
    depends_on:
      - database
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://database:27017/patients_db
    ports:
      - "8080:8080"
    restart: unless-stopped

  test-runner:
    image: maven:3.8.4-openjdk-17
    depends_on:
      - database
    volumes:
      - .:/app
    working_dir: /app
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://database:27017/patients_db
    command: ["/bin/sh", "-c", "sleep 10 && mvn test"]

volumes:
  mongo-data:
