spring.application.name=patient_service_pdp3
spring.data.mongodb.database=patients_db
spring.data.mongodb.uri=mongodb://localhost:27017/patients_db
#spring.data.mongodb.uri=mongodb://mongo:27017/patients_db

